--COMENTARIO
INSERT INTO `categories` (`name`, `order`) VALUES
('Centro Massaggi', '3'),
('Massaggiatrice', '5'),
('Massaggiatore', '2'),
('Massaggi Cinesi', ''),
('Centro Massaggi Cinese', ''),
('Massaggio Relax', ''),
('Massaggio Corpo a Corpo', ''),
('Massaggio Rilassante', ''),
('Massaggio Thailandese', ''),
('Massaggi Erotici', ''),
('Nuru Massage', ''),
('Massaggio Tantra', ''),
('Body Massage', ''),
('Massaggio ', ''),
('Massaggio Lingam', ''),
('Massaggio di Coppia', ''),
('Massaggi Orientali', ''),
('Massaggi Sexy', ''),
('Massaggi Sensuali', ''),
('Massaggio Prostatico', ''),
('Massaggi Hard', ''),
('Annunci Massaggi', ''),
('Massaggi Happy Ending', ''),
('Massaggi Hot', ''),
('Massaggio Anale ', ''),
('Massaggio Vaginale', ''),
('Massaggi xxx', ''),
('Massaggio Romantico', ''),
('Massaggio Thai', ''),
('Massaggi a Domicilio', ''),
('Massaggiatrici Cinesi ', ''),
('Massaggio Lesbico', ''),
('xxx Massaggi', ''),
('Massaggi Sessuali', ''),
('Soapy Massage ', ''),
('Massaggi Intimi', ''),
('Massaggi Particolari', ''),
('Massaggio Antistress', ''),
('Massaggio Giapponese', ''),
('Massaggi Eros', ''),
('Massaggio Naturista', ''),
('Massaggi Eccitanti', ''),
('Massaggi Privati ', ''),
('Annunci Massaggiatrici', ''),
('Massaggi Benessere ', ''),
('Massaggi Gratis', ''),
('Massaggi He', ''),
('Massaggi Integrali', ''),
('Massaggio con i Piedi', ''),
('Massaggi Speciali', ''),
('Cina Massaggi ', ''),
('Massaggi Asiatici', ''),
('Massaggi Cinesi Hot', ''),
('Massaggi Ose', ''),
('Massaggio Body', ''),
('Massaggio Inguinale', ''),
('Massaggi Spinti', ''),
('Massaggiatrici Hard', ''),
('Massaggi Cinesi xxx', ''),
('Massaggio con Finale ', ''),
('Massaggio Fortunato', ''),
('Massaggio Kashmiro', ''),
('Massaggi Nascosti', ''),
('Massaggio Maschile', ''),
('Massaggi Piccanti', ''),
('Massaggi tra Uomini', ''),
('Massaggiatrice xxx', ''),
('Massaggio Cinese Completo', ''),
('Massaggio Parti Intime', ''),
('Massaggio Body to Body', ''),
('Massaggio Imbarazzante', ''),
('Massaggio in Vasca', ''),
('Massaggio Sotto la Doccia', ''),
('Massaggio con la Lingua', ''),
('Massaggiatrici', '4'),
('Massaggiatori', '1');