INSERT INTO `main_menus` (`menu_name`, `menu_link`, `order_menu`, `title_seo`) VALUES
('Home', '', 1, 'Home Massaggi24'),
('Centri Massaggio', '#', 3, 'Centri Massaggio'),
('Massaggiatori', '#', 4, 'Massaggiatori'),
('Massaggiatrici', '#', 5, 'Massaggiatrici'),
('Massaggi Erotici', '#', 6, 'Massaggi Erotici'),
('Come Funziona', 'pagina.php?sezione=9', 7, 'Come Funziona Massaggi24'),
('Contatti', 'contattaci.php', 10, 'Contatti'),
('Massaggi', '#', 2, 'Massaggi'),
('Blog', 'lista-blog.php', 8, 'Blog Massaggi24'),
('Prezzi', 'prezzi', 9, 'Prezzi e Metodi di Pagamento');

INSERT INTO `sub_menus` (`id_main_menus`, `menu_name`, `menu_link`, `title_seo`) VALUES
(2, '-Centri Massaggio Agrigento ', 'massaggi-agrigento', 'Centri Massaggio Agrigento '),
(2, '-Centri Massaggio Alessandria', 'massaggi-alessandria', 'Centri Massaggio Alessandria'),
(2, '-Centri Massaggio Ancona', 'massaggi-ancona', 'Centri Massaggio Ancona'),
(2, '-Centri Massaggio Aosta', 'massaggi-aosta', 'Centri Massaggio Aosta'),
(2, '-Centri Massaggio Arezzo', 'massaggi-arezzo', 'Centri Massaggio Arezzo'),
(2, '-Centri Massaggio Ascoli Piceno', 'massaggi-ascoli-piceno', 'Centri Massaggio Ascoli Piceno'),
(2, '-Centri Massaggio Asti', 'massaggi-asti', 'Centri Massaggio Asti'),
(2, '-Centri Massaggio Avellino', 'massaggi-avellino', 'Centri Massaggio Avellino'),
(2, '-Centri Massaggio Bari', 'massaggi-bari', 'Centri Massaggio Bari'),
(2, '-Centri Massaggio Barletta Andria Trani', 'massaggi-barletta-andria-trani', 'Centri Massaggio Barletta Andria Trani'),
(2, '-Centri Massaggio Belluno', 'massaggi-belluno', 'Centri Massaggio Belluno'),
(2, '-Centri Massaggio Benevento', 'massaggi-benevento', 'Centri Massaggio Benevento'),
(2, '-Centri Massaggio Bergamo', 'massaggi-bergamo', 'Centri Massaggio Bergamo'),
(2, '-Centri Massaggio Biella', 'massaggi-biella', 'Centri Massaggio Biella'),
(2, '-Centri Massaggio Bologna', 'massaggi-bologna', 'Centri Massaggio Bologna'),
(2, '-Centri Massaggio Bolzano', 'massaggi-bolzano', 'Centri Massaggio Bolzano'),
(2, '-Centri Massaggio Brescia', 'massaggi-brescia', 'Centri Massaggio Brescia'),
(2, '-Centri Massaggio Brindisi', 'massaggi-brindisi', 'Centri Massaggio Brindisi'),
(2, '-Centri Massaggio Cagliari', 'massaggi-cagliari', 'Centri Massaggio Cagliari'),
(2, '-Centri Massaggio Caltanissetta', 'massaggi-caltanissetta', 'Centri Massaggio Caltanissetta'),
(2, '-Centri Massaggio Campobasso', 'massaggi-campobasso', 'Centri Massaggio Campobasso'),
(2, '-Centri Massaggio Carbonia Iglesias', 'massaggi-carbonia-iglesias', 'Centri Massaggio Carbonia Iglesias'),
(2, '-Centri Massaggio Caserta', 'massaggi-caserta', 'Centri Massaggio Caserta'),
(2, '-Centri Massaggio Catania', 'massaggi-catania', 'Centri Massaggio Catania'),
(2, '-Centri Massaggio Catanzaro', 'massaggi-catanzaro', 'Centri Massaggio Catanzaro'),
(2, '-Centri Massaggio Chieti', 'massaggi-chieti', 'Centri Massaggio Chieti'),
(2, '-Centri Massaggio Como', 'massaggi-como', 'Centri Massaggio Como'),
(2, '-Centri Massaggio Cosenza', 'massaggi-cosenza', 'Centri Massaggio Cosenza'),
(2, '-Centri Massaggio Cremona', 'massaggi-cremona', 'Centri Massaggio Cremona'),
(2, '-Centri Massaggio Crotone', 'massaggi-crotone', 'Centri Massaggio Crotone'),
(2, '-Centri Massaggio Cuneo', 'massaggi-cuneo', 'Centri Massaggio Cuneo'),
(2, '-Centri Massaggio Enna', 'massaggi-enna', 'Centri Massaggio Enna'),
(2, '-Centri Massaggio Fermo', 'massaggi-fermo', 'Centri Massaggio Fermo'),
(2, '-Centri Massaggio Ferrara', 'massaggi-ferrara', 'Centri Massaggio Ferrara'),
(2, '-Centri Massaggio Firenze', 'massaggi-firenze', 'Centri Massaggio Firenze'),
(2, '-Centri Massaggio Foggia', 'massaggi-foggia', 'Centri Massaggio Foggia'),
(2, '-Centri Massaggio Forlì Cesena', 'massaggi-forlec-cesena', 'Centri Massaggio Forlì Cesena'),
(2, '-Centri Massaggio Frosinone', 'massaggi-frosinone', 'Centri Massaggio Frosinone'),
(2, '-Centri Massaggio Genova', 'massaggi-genova', 'Centri Massaggio Genova'),
(2, '-Centri Massaggio Gorizia', 'massaggi-gorizia', 'Centri Massaggio Gorizia'),
(2, '-Centri Massaggio Grosseto', 'massaggi-grosseto', 'Centri Massaggio Grosseto'),
(2, '-Centri Massaggio Imperia', 'massaggi-imperia', 'Centri Massaggio Imperia'),
(2, '-Centri Massaggio Isernia', 'massaggi-isernia', 'Centri Massaggio Isernia'),
(2, '-Centri Massaggio L\'Aquila', 'massaggi-l\'aquila', 'Centri Massaggio L\'Aquila'),
(2, '-Centri Massaggio La Spezia', 'massaggi-la-spezia', 'Centri Massaggio La Spezia'),
(2, '-Centri Massaggio Latina', 'massaggi-latina', 'Centri Massaggio Latina'),
(2, '-Centri Massaggio Lecce', 'massaggi-lecce', 'Centri Massaggio Lecce'),
(2, '-Centri Massaggio Lecco', 'massaggi-lecco', 'Centri Massaggio Lecco'),
(2, '-Centri Massaggio Livorno', 'massaggi-livorno', 'Centri Massaggio Livorno'),
(2, '-Centri Massaggio Lodi', 'massaggi-lodi', 'Centri Massaggio Lodi'),
(2, '-Centri Massaggio Lucca', 'massaggi-lucca', 'Centri Massaggio Lucca'),
(2, '-Centri Massaggio Macerata', 'massaggi-macerata', 'Centri Massaggio Macerata'),
(2, '-Centri Massaggio Mantova', 'massaggi-mantova', 'Centri Massaggio Mantova'),
(2, '-Centri Massaggio Massa Carrara', 'massaggi-massa-carrara', 'Centri Massaggio Massa Carrara'),
(2, '-Centri Massaggio Matera', 'massaggi-matera', 'Centri Massaggio Matera'),
(2, '-Centri Massaggio Medio Campidano', 'massaggi-medio-campidano', 'Centri Massaggio Medio Campidano'),
(2, '-Centri Massaggio Messina', 'massaggi-messina', 'Centri Massaggio Messina'),
(2, '-Centri Massaggio Milano', 'massaggi-milano', 'Centri Massaggio Milano'),
(2, '-Centri Massaggio Modena', 'massaggi-modena', 'Centri Massaggio Modena'),
(2, '-Centri Massaggio Monza Brianza', 'massaggi-monza-e-della-brianza', 'Centri Massaggio Monza Brianza'),
(2, '-Centri Massaggio Napoli', 'massaggi-napoli', 'Centri Massaggio Napoli'),
(2, '-Centri Massaggio Novara', 'massaggi-novara', 'Centri Massaggio Novara'),
(2, '-Centri Massaggio Nuoro', 'massaggi-nuoro', 'Centri Massaggio Nuoro'),
(2, '-Centri Massaggio Ogliastra', 'massaggi-ogliastra', 'Centri Massaggio Ogliastra'),
(2, '-Centri Massaggio Olbia Tempio', 'massaggi-olbia-tempio', 'Centri Massaggio Olbia Tempio'),
(2, '-Centri Massaggio Oristano', 'massaggi-oristano', 'Centri Massaggio Oristano'),
(2, '-Centri Massaggio Padova', 'massaggi-padova', 'Centri Massaggio Padova'),
(2, '-Centri Massaggio Palermo', 'massaggi-palermo', 'Centri Massaggio Palermo'),
(2, '-Centri Massaggio Parma', 'massaggi-parma', 'Centri Massaggio Parma'),
(2, '-Centri Massaggio Pavia', 'massaggi-pavia', 'Centri Massaggio Pavia'),
(2, '-Centri Massaggio Perugia', 'massaggi-perugia', 'Centri Massaggio Perugia'),
(2, '-Centri Massaggio Pesaro Urbino', 'massaggi-pesaro-e-urbino', 'Centri Massaggio Pesaro Urbino'),
(2, '-Centri Massaggio Pescara', 'massaggi-pescara', 'Centri Massaggio Pescara'),
(2, '-Centri Massaggio Piacenza', 'massaggi-piacenza', 'Centri Massaggio Piacenza'),
(2, '-Centri Massaggio Pisa', 'massaggi-pisa', 'Centri Massaggio Pisa'),
(2, '-Centri Massaggio Pistoia', 'massaggi-pistoia', 'Centri Massaggio Pistoia'),
(2, '-Centri Massaggio Pordenone', 'massaggi-pordenone', 'Centri Massaggio Pordenone'),
(2, '-Centri Massaggio Potenza', 'massaggi-potenza', 'Centri Massaggio Potenza'),
(2, '-Centri Massaggio Prato', 'massaggi-prato', 'Centri Massaggio Prato'),
(2, '-Centri Massaggio Ragusa', 'massaggi-ragusa', 'Centri Massaggio Ragusa'),
(2, '-Centri Massaggio Ravenna', 'massaggi-ravenna', 'Centri Massaggio Ravenna'),
(2, '-Centri Massaggio Reggio Calabria', 'massaggi-reggio-calabria', 'Centri Massaggio Reggio Calabria'),
(2, '-Centri Massaggio Reggio Emilia', 'massaggi-reggio-emilia', 'Centri Massaggio Reggio Emilia'),
(2, '-Centri Massaggio Rieti', 'massaggi-rieti', 'Centri Massaggio Rieti'),
(2, '-Centri Massaggio Rimini', 'massaggi-rimini', 'Centri Massaggio Rimini'),
(2, '-Centri Massaggio Roma', 'massaggi-roma', 'Centri Massaggio Roma'),
(2, '-Centri Massaggio Rovigo', 'massaggi-rovigo', 'Centri Massaggio Rovigo'),
(2, '-Centri Massaggio Salerno', 'massaggi-salerno', 'Centri Massaggio Salerno'),
(2, '-Centri Massaggio Sassari', 'massaggi-sassari', 'Centri Massaggio Sassari'),
(2, '-Centri Massaggio Savona', 'massaggi-savona', 'Centri Massaggio Savona'),
(2, '-Centri Massaggio Siena', 'massaggi-siena', 'Centri Massaggio Siena'),
(2, '-Centri Massaggio Siracusa', 'massaggi-siracusa', 'Centri Massaggio Siracusa'),
(2, '-Centri Massaggio Sondrio', 'massaggi-sondrio', 'Centri Massaggio Sondrio'),
(2, '-Centri Massaggio Taranto', 'massaggi-taranto', 'Centri Massaggio Taranto'),
(2, '-Centri Massaggio Teramo', 'massaggi-teramo', 'Centri Massaggio Teramo'),
(2, '-Centri Massaggio Terni', 'massaggi-terni', 'Centri Massaggio Terni'),
(2, '-Centri Massaggio Torino', 'massaggi-torino', 'Centri Massaggio Torino'),
(2, '-Centri Massaggio Trapani', 'massaggi-trapani', 'Centri Massaggio Trapani'),
(2, '-Centri Massaggio Trento', 'massaggi-trento', 'Centri Massaggio Trento'),
(2, '-Centri Massaggio Treviso', 'massaggi-treviso', 'Centri Massaggio Treviso'),
(2, '-Centri Massaggio Trieste', 'massaggi-trieste', 'Centri Massaggio Trieste'),
(2, '-Centri Massaggio Udine', 'massaggi-udine', 'Centri Massaggio Udine'),
(2, '-Centri Massaggio Varese', 'massaggi-varese', 'Centri Massaggio Varese'),
(2, '-Centri Massaggio Venezia', 'massaggi-venezia', 'Centri Massaggio Venezia'),
(2, '-Centri Massaggio Verbano Cusio Ossola', 'massaggi-verbano-cusio-ossola', 'Centri Massaggio Verbano Cusio Ossola'),
(2, '-Centri Massaggio Vercelli', 'massaggi-vercelli', 'Centri Massaggio Vercelli'),
(2, '-Centri Massaggio Verona', 'massaggi-verona', 'Centri Massaggio Verona'),
(2, '-Centri Massaggio Vibo Valentia', 'massaggi-vibo-valentia', 'Centri Massaggio Vibo Valentia'),
(2, '-Centri Massaggio Vicenza', 'massaggi-vicenza', 'Centri Massaggio Vicenza'),
(2, '-Centri Massaggio Viterbo', 'massaggi-viterbo', 'Centri Massaggio Viterbo'),
(4, '-Massaggiatrici Agrigento', 'massaggi-agrigento', 'Massaggiatrici Agrigento'),
(4, '-Massaggiatrici Alessandria', 'massaggi-alessandria', 'Massaggiatrici Alessandria'),
(4, '-Massaggiatrici Ancona', 'massaggi-ancona', 'Massaggiatrici Ancona'),
(4, '-Massaggiatrici Aosta', 'massaggi-aosta', 'Massaggiatrici Aosta'),
(4, '-Massaggiatrici Arezzo', 'massaggi-arezzo', 'Massaggiatrici Arezzo'),
(4, '-Massaggiatrici Ascoli Piceno', 'massaggi-ascoli-piceno', 'Massaggiatrici Ascoli Piceno'),
(4, '-Massaggiatrici Asti', 'massaggi-asti', 'Massaggiatrici Asti'),
(4, '-Massaggiatrici Avellino', 'massaggi-avellino', 'Massaggiatrici Avellino'),
(4, '-Massaggiatrici Bari', 'massaggi-bari', 'Massaggiatrici Bari'),
(4, '-Massaggiatrici Barletta Andria Trani', 'massaggi-barletta-andria-trani', 'Massaggiatrici Barletta Andria Trani'),
(4, '-Massaggiatrici Belluno', 'massaggi-belluno', 'Massaggiatrici Belluno'),
(4, '-Massaggiatrici Benevento', 'massaggi-benevento', 'Massaggiatrici Benevento'),
(4, '-Massaggiatrici Bergamo', 'massaggi-bergamo', 'Massaggiatrici Bergamo'),
(4, '-Massaggiatrici Biella', 'massaggi-biella', 'Massaggiatrici Biella'),
(4, '-Massaggiatrici Bologna', 'massaggi-bologna', 'Massaggiatrici Bologna'),
(4, '-Massaggiatrici Bolzano', 'massaggi-bolzano', 'Massaggiatrici Bolzano'),
(4, '-Massaggiatrici Brescia', 'massaggi-brescia', 'Massaggiatrici Brescia'),
(4, '-Massaggiatrici Brindisi', 'massaggi-brindisi', 'Massaggiatrici Brindisi'),
(4, '-Massaggiatrici Cagliari', 'massaggi-cagliari', 'Massaggiatrici Cagliari'),
(4, '-Massaggiatrici Caltanissetta', 'massaggi-caltanissetta', 'Massaggiatrici Caltanissetta'),
(4, '-Massaggiatrici Campobasso', 'massaggi-campobasso', 'Massaggiatrici Campobasso'),
(4, '-Massaggiatrici Carbonia Iglesias', 'massaggi-carbonia-iglesias', 'Massaggiatrici Carbonia Iglesias'),
(4, '-Massaggiatrici Caserta', 'massaggi-caserta', 'Massaggiatrici Caserta'),
(4, '-Massaggiatrici Catania', 'massaggi-catania', 'Massaggiatrici Catania'),
(4, '-Massaggiatrici Catanzaro', 'massaggi-catanzaro', 'Massaggiatrici Catanzaro'),
(4, '-Massaggiatrici Chieti', 'massaggi-chieti', 'Massaggiatrici Chieti'),
(4, '-Massaggiatrici Como', 'massaggi-como', 'Massaggiatrici Como'),
(4, '-Massaggiatrici Cosenza', 'massaggi-cosenza', 'Massaggiatrici Cosenza'),
(4, '-Massaggiatrici Cremona', 'massaggi-cremona', 'Massaggiatrici Cremona'),
(4, '-Massaggiatrici Crotone', 'massaggi-crotone', 'Massaggiatrici Crotone'),
(4, '-Massaggiatrici Cuneo', 'massaggi-cuneo', 'Massaggiatrici Cuneo'),
(4, '-Massaggiatrici Enna', 'massaggi-enna', 'Massaggiatrici Enna'),
(4, '-Massaggiatrici Fermo', 'massaggi-fermo', 'Massaggiatrici Fermo'),
(4, '-Massaggiatrici Ferrara', 'massaggi-ferrara', 'Massaggiatrici Ferrara'),
(4, '-Massaggiatrici Firenze', 'massaggi-firenze', 'Massaggiatrici Firenze'),
(4, '-Massaggiatrici Foggia', 'massaggi-foggia', 'Massaggiatrici Foggia'),
(4, '-Massaggiatrici Forlì Cesena', 'massaggi-forlec-cesena', 'Massaggiatrici Forlì Cesena'),
(4, '-Massaggiatrici Frosinone', 'massaggi-frosinone', 'Massaggiatrici Frosinone'),
(4, '-Massaggiatrici Genova', 'massaggi-genova', 'Massaggiatrici Genova'),
(4, '-Massaggiatrici Gorizia', 'massaggi-gorizia', 'Massaggiatrici Gorizia'),
(4, '-Massaggiatrici Grosseto', 'massaggi-grosseto', 'Massaggiatrici Grosseto'),
(4, '-Massaggiatrici Imperia', 'massaggi-imperia', 'Massaggiatrici Imperia'),
(4, '-Massaggiatrici Isernia', 'massaggi-isernia', 'Massaggiatrici Isernia'),
(4, '-Massaggiatrici L\'Aquila ', 'massaggi-l\'aquila', 'Massaggiatrici L\'Aquila '),
(4, '-Massaggiatrici La Spezia', 'massaggi-la-spezia', 'Massaggiatrici La Spezia'),
(4, '-Massaggiatrici Latina', 'massaggi-latina', 'Massaggiatrici Latina'),
(4, '-Massaggiatrici Lecce', 'massaggi-lecce', 'Massaggiatrici Lecce'),
(4, '-Massaggiatrici Lecco', 'massaggi-lecco', 'Massaggiatrici Lecco'),
(4, '-Massaggiatrici Livorno', 'massaggi-livorno', 'Massaggiatrici Livorno'),
(4, '-Massaggiatrici Lodi', 'massaggi-lodi', 'Massaggiatrici Lodi'),
(4, '-Massaggiatrici Lucca', 'massaggi-lucca', 'Massaggiatrici Lucca'),
(4, '-Massaggiatrici Macerata', 'massaggi-macerata', 'Massaggiatrici Macerata'),
(4, '-Massaggiatrici Mantova', 'massaggi-mantova', 'Massaggiatrici Mantova'),
(4, '-Massaggiatrici Massa Carrara', 'massaggi-massa-carrara', 'Massaggiatrici Massa Carrara'),
(4, '-Massaggiatrici Matera', 'massaggi-matera', 'Massaggiatrici Matera'),
(4, '-Massaggiatrici Medio Campidano', 'massaggi-medio-campidano', 'Massaggiatrici Medio Campidano'),
(4, '-Massaggiatrici Messina', 'massaggi-messina', 'Massaggiatrici Messina'),
(4, '-Massaggiatrici Milano', 'massaggi-milano', 'Massaggiatrici Milano'),
(4, '-Massaggiatrici Modena', 'massaggi-modena', 'Massaggiatrici Modena'),
(4, '-Massaggiatrici Monza Brianza', 'massaggi-monza-e-della-brianza', 'Massaggiatrici Monza Brianza'),
(4, '-Massaggiatrici Napoli', 'massaggi-napoli', 'Massaggiatrici Napoli'),
(4, '-Massaggiatrici Novara', 'massaggi-novara', 'Massaggiatrici Novara'),
(4, '-Massaggiatrici Nuoro', 'massaggi-nuoro', 'Massaggiatrici Nuoro'),
(4, '-Massaggiatrici Ogliastra', 'massaggi-ogliastra', 'Massaggiatrici Ogliastra'),
(4, '-Massaggiatrici Olbia Tempio', 'massaggi-olbia-tempio', 'Massaggiatrici Olbia Tempio'),
(4, '-Massaggiatrici Oristano', 'massaggi-oristano', 'Massaggiatrici Oristano'),
(4, '-Massaggiatrici Padova', 'massaggi-padova', 'Massaggiatrici Padova'),
(4, '-Massaggiatrici Palermo', 'massaggi-palermo', 'Massaggiatrici Palermo'),
(4, '-Massaggiatrici Parma', 'massaggi-parma', 'Massaggiatrici Parma'),
(4, '-Massaggiatrici Pavia', 'massaggi-pavia', 'Massaggiatrici Pavia'),
(4, '-Massaggiatrici Perugia', 'massaggi-perugia', 'Massaggiatrici Perugia'),
(4, '-Massaggiatrici Pesaro Urbino', 'massaggi-pesaro-e-urbino', 'Massaggiatrici Pesaro Urbino'),
(4, '-Massaggiatrici Pescara', 'massaggi-pescara', 'Massaggiatrici Pescara'),
(4, '-Massaggiatrici Piacenza', 'massaggi-piacenza', 'Massaggiatrici Piacenza'),
(4, '-Massaggiatrici Pisa', 'massaggi-pisa', 'Massaggiatrici Pisa'),
(4, '-Massaggiatrici Pistoia', 'massaggi-pistoia', 'Massaggiatrici Pistoia'),
(4, '-Massaggiatrici Pordenone', 'massaggi-pordenone', 'Massaggiatrici Pordenone'),
(4, '-Massaggiatrici Potenza', 'massaggi-potenza', 'Massaggiatrici Potenza'),
(4, '-Massaggiatrici Prato', 'massaggi-prato', 'Massaggiatrici Prato'),
(4, '-Massaggiatrici Ragusa', 'massaggi-ragusa', 'Massaggiatrici Ragusa'),
(4, '-Massaggiatrici Ravenna', 'massaggi-ravenna', 'Massaggiatrici Ravenna'),
(4, '-Massaggiatrici Reggio Calabria', 'massaggi-reggio-calabria', 'Massaggiatrici Reggio Calabria'),
(4, '-Massaggiatrici Reggio Emilia', 'massaggi-reggio-emilia', 'Massaggiatrici Reggio Emilia'),
(4, '-Massaggiatrici Rieti', 'massaggi-rieti', 'Massaggiatrici Rieti'),
(4, '-Massaggiatrici Rimini', 'massaggi-rimini', 'Massaggiatrici Rimini'),
(4, '-Massaggiatrici Roma', 'massaggi-roma', 'Massaggiatrici Roma'),
(4, '-Massaggiatrici Rovigo', 'massaggi-rovigo', 'Massaggiatrici Rovigo'),
(4, '-Massaggiatrici Salerno', 'massaggi-salerno', 'Massaggiatrici Salerno'),
(4, '-Massaggiatrici Sassari', 'massaggi-sassari', 'Massaggiatrici Sassari'),
(4, '-Massaggiatrici Savona', 'massaggi-savona', 'Massaggiatrici Savona'),
(4, '-Massaggiatrici Siena', 'massaggi-siena', 'Massaggiatrici Siena'),
(4, '-Massaggiatrici Siracusa', 'massaggi-siracusa', 'Massaggiatrici Siracusa'),
(4, '-Massaggiatrici Sondrio', 'massaggi-sondrio', 'Massaggiatrici Sondrio'),
(4, '-Massaggiatrici Taranto', 'massaggi-taranto', 'Massaggiatrici Taranto'),
(4, '-Massaggiatrici Teramo', 'massaggi-teramo', 'Massaggiatrici Teramo'),
(4, '-Massaggiatrici Terni', 'massaggi-terni', 'Massaggiatrici Terni'),
(4, '-Massaggiatrici Torino', 'massaggi-torino', 'Massaggiatrici Torino'),
(4, '-Massaggiatrici Trapani', 'massaggi-trapani', 'Massaggiatrici Trapani'),
(4, '-Massaggiatrici Trento', 'massaggi-trento', 'Massaggiatrici Trento'),
(4, '-Massaggiatrici Treviso', 'massaggi-treviso', 'Massaggiatrici Treviso'),
(4, '-Massaggiatrici Trieste', 'massaggi-trieste', 'Massaggiatrici Trieste'),
(4, '-Massaggiatrici Udine', 'massaggi-udine', 'Massaggiatrici Udine'),
(4, '-Massaggiatrici Varese', 'massaggi-varese', 'Massaggiatrici Varese'),
(4, '-Massaggiatrici Venezia', 'massaggi-venezia', 'Massaggiatrici Venezia'),
(4, '-Massaggiatrici Verbano-Cusio-Ossola', 'massaggi-verbano-cusio-ossola', 'Massaggiatrici Verbano-Cusio-Ossola'),
(4, '-Massaggiatrici Vercelli', 'massaggi-vercelli', 'Massaggiatrici Vercelli'),
(4, '-Massaggiatrici Verona', 'massaggi-verona', 'Massaggiatrici Verona'),
(4, '-Massaggiatrici Vibo Valentia', 'massaggi-vibo-valentia', 'Massaggiatrici Vibo Valentia'),
(4, '-Massaggiatrici Vicenza', 'massaggi-vicenza', 'Massaggiatrici Vicenza'),
(4, '-Massaggiatrici Viterbo', 'massaggi-viterbo', 'Massaggiatrici Viterbo'),
(3, '-Massaggiatori Agrigento', 'massaggi-agrigento', 'Massaggiatori Agrigento'),
(3, '-Massaggiatori Alessandria', 'massaggi-alessandria', 'Massaggiatori Alessandria'),
(3, '-Massaggiatori Ancona', 'massaggi-ancona', 'Massaggiatori Ancona'),
(3, '-Massaggiatori Aosta', 'massaggi-aosta', 'Massaggiatori Aosta'),
(3, '-Massaggiatori Arezzo', 'massaggi-arezzo', 'Massaggiatori Arezzo'),
(3, '-Massaggiatori Ascoli Piceno', 'massaggi-ascoli-piceno', 'Massaggiatori Ascoli Piceno'),
(3, '-Massaggiatori Asti', 'massaggi-asti', 'Massaggiatori Asti'),
(3, '-Massaggiatori Avellino', 'massaggi-avellino', 'Massaggiatori Avellino'),
(3, '-Massaggiatori Bari', 'massaggi-bari', 'Massaggiatori Bari'),
(3, '-Massaggiatori Barletta-Andria-Trani', 'massaggi-barletta-andria-trani', 'Massaggiatori Barletta-Andria-Trani'),
(3, '-Massaggiatori Belluno', 'massaggi-belluno', 'Massaggiatori Belluno'),
(3, '-Massaggiatori Benevento', 'massaggi-benevento', 'Massaggiatori Benevento'),
(3, '-Massaggiatori Bergamo', 'massaggi-bergamo', 'Massaggiatori Bergamo'),
(3, '-Massaggiatori Biella', 'massaggi-biella', 'Massaggiatori Biella'),
(3, '-Massaggiatori Bologna', 'massaggi-bologna', 'Massaggiatori Bologna'),
(3, '-Massaggiatori Bolzano', 'massaggi-bolzano', 'Massaggiatori Bolzano'),
(3, '-Massaggiatori Brescia', 'massaggi-brescia', 'Massaggiatori Brescia'),
(3, '-Massaggiatori Brindisi', 'massaggi-brindisi', 'Massaggiatori Brindisi'),
(3, '-Massaggiatori Cagliari', 'massaggi-cagliari', 'Massaggiatori Cagliari'),
(3, '-Massaggiatori Caltanissetta', 'massaggi-caltanissetta', 'Massaggiatori Caltanissetta'),
(3, '-Massaggiatori Campobasso', 'massaggi-campobasso', 'Massaggiatori Campobasso'),
(3, '-Massaggiatori Carbonia Iglesias', 'massaggi-carbonia-iglesias', 'Massaggiatori Carbonia Iglesias'),
(3, '-Massaggiatori Caserta', 'massaggi-caserta', 'Massaggiatori Caserta'),
(3, '-Massaggiatori Catania', 'massaggi-catania', 'Massaggiatori Catania'),
(3, '-Massaggiatori Catanzaro', 'massaggi-catanzaro', 'Massaggiatori Catanzaro'),
(3, '-Massaggiatori Chieti', 'massaggi-chieti', 'Massaggiatori Chieti'),
(3, '-Massaggiatori Como', 'massaggi-como', 'Massaggiatori Como'),
(3, '-Massaggiatori Cosenza', 'massaggi-cosenza', 'Massaggiatori Cosenza'),
(3, '-Massaggiatori Cremona', 'massaggi-cremona', 'Massaggiatori Cremona'),
(3, '-Massaggiatori Crotone', 'massaggi-crotone', 'Massaggiatori Crotone'),
(3, '-Massaggiatori Cuneo', 'massaggi-cuneo', 'Massaggiatori Cuneo'),
(3, '-Massaggiatori Enna', 'massaggi-enna', 'Massaggiatori Enna'),
(3, '-Massaggiatori Fermo', 'massaggi-fermo', 'Massaggiatori Fermo'),
(3, '-Massaggiatori Ferrara', 'massaggi-ferrara', 'Massaggiatori Ferrara'),
(3, '-Massaggiatori Firenze', 'massaggi-firenze', 'Massaggiatori Firenze'),
(3, '-Massaggiatori Foggia', 'massaggi-foggia', 'Massaggiatori Foggia'),
(3, '-Massaggiatori Forlì Cesena', 'massaggi-forlec-cesena', 'Massaggiatori Forlì Cesena'),
(3, '-Massaggiatori Frosinone', 'massaggi-frosinone', 'Massaggiatori Frosinone'),
(3, '-Massaggiatori Genova', 'massaggi-genova', 'Massaggiatori Genova'),
(3, '-Massaggiatori Gorizia', 'massaggi-gorizia', 'Massaggiatori Gorizia'),
(3, '-Massaggiatori Grosseto', 'massaggi-grosseto', 'Massaggiatori Grosseto'),
(3, '-Massaggiatori Imperia', 'massaggi-imperia', 'Massaggiatori Imperia'),
(3, '-Massaggiatori Isernia', 'massaggi-isernia', 'Massaggiatori Isernia'),
(3, '-Massaggiatori L\'Aquila', 'massaggi-l\'aquila', 'Massaggiatori L\'Aquila'),
(3, '-Massaggiatori La Spezia', 'massaggi-la-spezia', 'Massaggiatori La Spezia'),
(3, '-Massaggiatori Latina', 'massaggi-latina', 'Massaggiatori Latina'),
(3, '-Massaggiatori Lecce', 'massaggi-lecce', 'Massaggiatori Lecce'),
(3, '-Massaggiatori Lecco', 'massaggi-lecco', 'Massaggiatori Lecco'),
(3, '-Massaggiatori Livorno', 'massaggi-livorno', 'Massaggiatori Livorno'),
(3, '-Massaggiatori Lodi', 'massaggi-lodi', 'Massaggiatori Lodi'),
(3, '-Massaggiatori Lucca', 'massaggi-lucca', 'Massaggiatori Lucca'),
(3, '-Massaggiatori Macerata', 'massaggi-macerata', 'Massaggiatori Macerata'),
(3, '-Massaggiatori Mantova', 'massaggi-mantova', 'Massaggiatori Mantova'),
(3, '-Massaggiatori Massa Carrara', 'massaggi-massa-carrara', 'Massaggiatori Massa Carrara'),
(3, '-Massaggiatori Matera', 'massaggi-matera', 'Massaggiatori Matera'),
(3, '-Massaggiatori Medio Campidano', 'massaggi-medio-campidano', 'Massaggiatori Medio Campidano'),
(3, '-Massaggiatori Messina', 'massaggi-messina', 'Massaggiatori Messina'),
(3, '-Massaggiatori Milano', 'massaggi-milano', 'Massaggiatori Milano'),
(3, '-Massaggiatori Modena', 'massaggi-modena', 'Massaggiatori Modena'),
(3, '-Massaggiatori Monza Brianza', 'massaggi-monza-e-della-brianza', 'Massaggiatori Monza Brianza'),
(3, '-Massaggiatori Napoli', 'massaggi-napoli', 'Massaggiatori Napoli'),
(3, '-Massaggiatori Novara', 'massaggi-novara', 'Massaggiatori Novara'),
(3, '-Massaggiatori Nuoro', 'massaggi-nuoro', 'Massaggiatori Nuoro'),
(3, '-Massaggiatori Ogliastra', 'massaggi-ogliastra', 'Massaggiatori Ogliastra'),
(3, '-Massaggiatori Olbia Tempio', 'massaggi-olbia-tempio', 'Massaggiatori Olbia Tempio'),
(3, '-Massaggiatori Oristano', 'massaggi-oristano', 'Massaggiatori Oristano'),
(3, '-Massaggiatori Padova', 'massaggi-padova', 'Massaggiatori Padova'),
(3, '-Massaggiatori Palermo', 'massaggi-palermo', 'Massaggiatori Palermo'),
(3, '-Massaggiatori Parma', 'massaggi-parma', 'Massaggiatori Parma'),
(3, '-Massaggiatori Pavia', 'massaggi-pavia', 'Massaggiatori Pavia'),
(3, '-Massaggiatori Perugia', 'massaggi-perugia', 'Massaggiatori Perugia'),
(3, '-Massaggiatori Pesaro Urbino', 'massaggi-pesaro-e-urbino', 'Massaggiatori Pesaro Urbino'),
(3, '-Massaggiatori Pescara', 'massaggi-pescara', 'Massaggiatori Pescara'),
(3, '-Massaggiatori Piacenza', 'massaggi-piacenza', 'Massaggiatori Piacenza'),
(3, '-Massaggiatori Pisa', 'massaggi-pisa', 'Massaggiatori Pisa'),
(3, '-Massaggiatori Pistoia', 'massaggi-pistoia', 'Massaggiatori Pistoia'),
(3, '-Massaggiatori Pordenone', 'massaggi-pordenone', 'Massaggiatori Pordenone'),
(3, '-Massaggiatori Potenza', 'massaggi-potenza', 'Massaggiatori Potenza'),
(3, '-Massaggiatori Prato', 'massaggi-prato', 'Massaggiatori Prato'),
(3, '-Massaggiatori Ragusa', 'massaggi-ragusa', 'Massaggiatori Ragusa'),
(3, '-Massaggiatori Ravenna', 'massaggi-ravenna', 'Massaggiatori Ravenna'),
(3, '-Massaggiatori Reggio Calabria', 'massaggi-reggio-calabria', 'Massaggiatori Reggio Calabria'),
(3, '-Massaggiatori Reggio Emilia', 'massaggi-reggio-emilia', 'Massaggiatori Reggio Emilia'),
(3, '-Massaggiatori Rieti', 'massaggi-rieti', 'Massaggiatori Rieti'),
(3, '-Massaggiatori Rimini', 'massaggi-rimini', 'Massaggiatori Rimini'),
(3, '-Massaggiatori Roma', 'massaggi-roma', 'Massaggiatori Roma'),
(3, '-Massaggiatori Rovigo', 'massaggi-rovigo', 'Massaggiatori Rovigo'),
(3, '-Massaggiatori Salerno', 'massaggi-salerno', 'Massaggiatori Salerno'),
(3, '-Massaggiatori Sassari', 'massaggi-sassari', 'Massaggiatori Sassari'),
(3, '-Massaggiatori Savona', 'massaggi-savona', 'Massaggiatori Savona'),
(3, '-Massaggiatori Siena', 'massaggi-siena', 'Massaggiatori Siena'),
(3, '-Massaggiatori Siracusa', 'massaggi-siracusa', 'Massaggiatori Siracusa'),
(3, '-Massaggiatori Sondrio', 'massaggi-sondrio', 'Massaggiatori Sondrio'),
(3, '-Massaggiatori Taranto', 'massaggi-taranto', 'Massaggiatori Taranto'),
(3, '-Massaggiatori Teramo', 'massaggi-teramo', 'Massaggiatori Teramo'),
(3, '-Massaggiatori Terni', 'massaggi-terni', 'Massaggiatori Terni'),
(3, '-Massaggiatori Torino', 'massaggi-torino', 'Massaggiatori Torino'),
(3, '-Massaggiatori Trapani', 'massaggi-trapani', 'Massaggiatori Trapani'),
(3, '-Massaggiatori Trento', 'massaggi-trento', 'Massaggiatori Trento'),
(3, '-Massaggiatori Treviso', 'massaggi-treviso', 'Massaggiatori Treviso'),
(3, '-Massaggiatori Trieste', 'massaggi-trieste', 'Massaggiatori Trieste'),
(3, '-Massaggiatori Udine', 'massaggi-udine', 'Massaggiatori Udine'),
(3, '-Massaggiatori Varese', 'massaggi-varese', 'Massaggiatori Varese'),
(3, '-Massaggiatori Venezia', 'massaggi-venezia', 'Massaggiatori Venezia'),
(3, '-Massaggiatori Verbano-Cusio-Ossola', 'massaggi-verbano-cusio-ossola', 'Massaggiatori Verbano-Cusio-Ossola'),
(3, '-Massaggiatori Vercelli', 'massaggi-vercelli', 'Massaggiatori Vercelli'),
(3, '-Massaggiatori Verona', 'massaggi-verona', 'Massaggiatori Verona'),
(3, '-Massaggiatori Vibo Valentia', 'massaggi-vibo-valentia', 'Massaggiatori Vibo Valentia'),
(3, '-Massaggiatori Vicenza', 'massaggi-vicenza', 'Massaggiatori Vicenza'),
(3, '-Massaggiatori Viterbo', 'massaggi-viterbo', 'Massaggiatori Viterbo'),
(5, '-Massaggio Cinese', '', 'Massaggio Cinese'),
(5, '-Massaggio Prostatico', '', 'Massaggio Prostatico'),
(5, '-Massaggio Tantra', '', 'Massaggio Tantra'),
(5, '-Total Body Massage', '', 'Total Body Massage'),
(5, '-Massaggio Erotico', '', 'Massaggio Erotico'),
(5, '-Massaggio Yoni', '', 'Massaggio Yoni'),
(5, '-Massaggio Lingam', '', 'Massaggio Lingam'),
(5, '-Nuru Massage', '', 'Nuru Massage'),
(5, '-Massaggio Orientale', '', 'Massaggio Orientale'),
(5, '-Massaggio Relax', '', 'Massaggio Relax'),
(5, '-Massaggio Corpo a Corpo', '', 'Massaggio Corpo a Corpo'),
(5, '-Massaggio Rilassante', '', 'Massaggio Rilassante'),
(5, '-Massaggio Thailandese', '', 'Massaggio Thailandese'),
(5, '-Massaggio Lingam', 'massaggio-lingam', 'Massaggio Lingam'),
(5, '-Massaggi Orientali', 'massaggi-orientali', 'Massaggi Orientali'),
(5, '-Massaggi Sexy', 'massaggi-sexy', 'Massaggi Sexy'),
(5, '-Massaggio Yoni', 'massaggio-yoni', 'Massaggio Yoni'),
(5, '-Annunci Massaggi', 'annunci-massaggi', 'Annunci Massaggi'),
(5, '-Body Massage', 'body-massage', 'Body Massage'),
(5, '-Massaggi Happy Ending', 'Massaggi-Happy-Ending', 'Massaggi Happy Ending'),
(5, '-Massaggi Hot', 'massaggi-hot', 'Massaggi Hot'),
(5, '-Massaggi Sensuali', 'massaggio-lingam', 'Massaggi Sensuali'),
(5, '-Massaggio Anale ', 'massaggio-anale ', 'Massaggio Anale'),
(5, '-Massaggio Vaginale', 'massaggio-vaginale', 'Massaggio Vaginale'),
(5, '-Massaggi xxx', 'massaggi-xxx', 'Massaggi xxx'),
(5, '-Massaggio Romantico', 'massaggio-romantico', 'Massaggio Romantico'),
(5, '-Massaggio Thai', 'massaggio-thai', 'Massaggio Thai'),
(5, '-Massaggi a Domicilio', 'massaggi-a-domicilio', 'Massaggi a Domicilio'),
(5, '-Massaggiatrici Cinesi ', 'massaggiatrici-cinesi ', 'Massaggiatrici Cinesi'),
(5, '-Massaggio di Coppia', 'massaggio-di-coppia', 'Massaggio di Coppia'),
(5, '-Massaggio Lesbico', 'massaggio-lesbico', 'Massaggio Lesbico'),
(5, '-xxx Massaggi', 'xxx-massaggi', 'xxx Massaggi'),
(5, '-Massaggi Sessuali', 'massaggi-sessuali', 'Massaggi Sessuali'),
(5, '-Soapy Massage ', 'soapy-massage ', 'Soapy Massage '),
(5, '-Massaggi Intimi', 'massaggi-intimi', 'Massaggi Intimi'),
(5, '-Massaggi Particolari', 'massaggi-particolari', 'Massaggi Particolari'),
(5, '-Massaggio Antistress', 'massaggio-antistress', 'Massaggio Antistress'),
(5, '-Massaggio Corpo a Corpo', 'massaggio-corpo-a-corpo', 'Massaggio Corpo a Corpo'),
(5, '-Massaggio Giapponese', 'massaggio-giapponese', 'Massaggio Giapponese'),
(5, '-Massaggio Relax', 'massaggio-relax', 'Massaggio Relax'),
(5, '-Massaggi Eros', 'massaggi-eros', 'Massaggi Eros'),
(5, '-Massaggio Naturista', 'massaggio-naturista', 'Massaggio Naturista'),
(5, '-Massaggi Eccitanti', 'massaggi-eccitanti', 'Massaggi Eccitanti'),
(5, '-Massaggi Privati ', 'massaggi-privati ', 'Massaggi Privati'),
(5, '-Annunci Massaggiatrici', 'annunci-massaggiatrici', 'Annunci Massaggiatrici'),
(5, '-Massaggi Benessere ', 'massaggi-benessere ', 'Massaggi Benessere '),
(5, '-Massaggi Gratis', 'massaggi-gratis', 'Massaggi Gratis'),
(5, '-Massaggi He', 'massaggi-he', 'Massaggi He'),
(5, '-Massaggi Integrali', 'massaggi-integrali', 'Massaggi Integrali'),
(5, '-Massaggio con i Piedi', 'massaggio-con-i-piedi', 'Massaggio con i Piedi'),
(5, '-Massaggi Speciali', 'massaggi-speciali', 'Massaggi Speciali'),
(5, '-Cina Massaggi ', 'cina-massaggi ', 'Cina Massaggi '),
(5, '-Massaggi Asiatici', 'massaggi-asiatici', 'Massaggi Asiatici'),
(5, '-Massaggi Cinesi Hot', 'massaggi-cinesi-hot', 'Massaggi Cinesi Hot'),
(5, '-Massaggi Ose', 'massaggi-ose', 'Massaggi Ose'),
(5, '-Massaggio Body', 'massaggio-body', 'Massaggio Body'),
(5, '-Massaggio Inguinale', 'massaggio-inguinale', 'Massaggio Inguinale'),
(5, '-Massaggi Spinti', 'massaggi-spinti', 'Massaggi Spinti'),
(5, '-Massaggiatrici Hard', 'massaggiatrici-hard', 'Massaggiatrici Hard'),
(5, '-Massaggi Cinesi xxx', 'massaggi-cinesi-xxx', 'Massaggi Cinesi xxx'),
(5, '-Massaggio con Finale ', 'massaggio-con-finale ', 'Massaggio con Finale '),
(5, '-Massaggio Fortunato', 'massaggio-fortunato', 'Massaggio Fortunato'),
(5, '-Massaggio Kashmiro', 'massaggio-kashmiro', 'Massaggio Kashmiro'),
(5, '-Massaggi Nascosti', 'massaggi-nascosti', 'Massaggi Nascosti'),
(5, '-Massaggio Maschile', 'massaggio-maschile', 'Massaggio Maschile'),
(5, '-Massaggi Piccanti', 'massaggi-piccanti', 'Massaggi Piccanti'),
(5, '-Massaggi tra Uomini', 'massaggi-tra-uomini', 'Massaggi tra Uomini'),
(5, '-Massaggiatrice xxx', 'massaggiatrice-xxx', 'Massaggiatrice xxx'),
(5, '-Massaggio Cinese Completo', 'massaggio-cinese-completo', 'Massaggio Cinese Completo'),
(5, '-Massaggio Parti Intime', 'massaggio-parti-intime', 'Massaggio Parti Intime'),
(5, '-Massaggio Body to Body', 'massaggio-body-to-body', 'Massaggio Body to Body'),
(5, '-Massaggio Imbarazzante', 'massaggio-imbarazzante', 'Massaggio Imbarazzante'),
(5, '-Massaggio in Vasca', 'massaggio-in-vasca', 'Massaggio in Vasca'),
(5, '-Massaggio Sotto la Doccia', 'massaggio-sotto-la-doccia', 'Massaggio Sotto la Doccia'),
(5, '-Massaggio con la Lingua', 'massaggio-con-la-lingua', 'Massaggio con la Lingua'),
(8, '-Massaggi Agrigento', 'massaggi-agrigento', 'Massaggi Agrigento'),
(8, '-Massaggi Alessandria', 'massaggi-alessandria', 'Massaggi Alessandria'),
(8, '-Massaggi Ancona', 'massaggi-ancona', 'Massaggi Ancona'),
(8, '-Massaggi Aosta', 'massaggi-aosta', 'Massaggi Aosta'),
(8, '-Massaggi Arezzo', 'massaggi-arezzo', 'Massaggi Arezzo'),
(8, '-Massaggi Ascoli Piceno', 'massaggi-ascoli-piceno', 'Massaggi Ascoli Piceno'),
(8, '-Massaggi Asti', 'massaggi-asti', 'Massaggi Asti'),
(8, '-Massaggi Avellino', 'massaggi-avellino', 'Massaggi Avellino'),
(8, '-Massaggi Bari', 'massaggi-bari', 'Massaggi Bari'),
(8, '-Massaggi Barletta Andria Trani', 'massaggi-barletta-andria-trani', 'Massaggi Barletta Andria Trani'),
(8, '-Massaggi Belluno', 'massaggi-belluno', 'Massaggi Belluno'),
(8, '-Massaggi Benevento', 'massaggi-benevento', 'Massaggi Benevento'),
(8, '-Massaggi Bergamo', 'massaggi-bergamo', 'Massaggi Bergamo'),
(8, '-Massaggi Biella', 'massaggi-biella', 'Massaggi Biella'),
(8, '-Massaggi Bologna', 'massaggi-bologna', 'Massaggi Bologna'),
(8, '-Massaggi Bolzano', 'massaggi-bolzano', 'Massaggi Bolzano'),
(8, '-Massaggi Brescia', 'massaggi-brescia', 'Massaggi Brescia'),
(8, '-Massaggi Brindisi', 'massaggi-brindisi', 'Massaggi Brindisi'),
(8, '-Massaggi Cagliari', 'massaggi-cagliari', 'Massaggi Cagliari'),
(8, '-Massaggi Caltanissetta', 'massaggi-caltanissetta', 'Massaggi Caltanissetta'),
(8, '-Massaggi Campobasso', 'massaggi-campobasso', 'Massaggi Campobasso'),
(8, '-Massaggi Carbonia Iglesias', 'massaggi-carbonia-iglesias', 'Massaggi Carbonia Iglesias'),
(8, '-Massaggi Caserta', 'massaggi-caserta', 'Massaggi Caserta'),
(8, '-Massaggi Catania', 'massaggi-catania', 'Massaggi Catania'),
(8, '-Massaggi Catanzaro', 'massaggi-catanzaro', 'Massaggi Catanzaro'),
(8, '-Massaggi Chieti', 'massaggi-chieti', 'Massaggi Chieti'),
(8, '-Massaggi Como', 'massaggi-como', 'Massaggi Como'),
(8, '-Massaggi Cosenza', 'massaggi-cosenza', 'Massaggi Cosenza'),
(8, '-Massaggi Cremona', 'massaggi-cremona', 'Massaggi Cremona'),
(8, '-Massaggi Crotone', 'massaggi-crotone', 'Massaggi Crotone'),
(8, '-Massaggi Cuneo', 'massaggi-cuneo', 'Massaggi Cuneo'),
(8, '-Massaggi Enna', 'massaggi-enna', 'Massaggi Enna'),
(8, '-Massaggi Fermo', 'massaggi-fermo', 'Massaggi Fermo'),
(8, '-Massaggi Ferrara', 'massaggi-ferrara', 'Massaggi Ferrara'),
(8, '-Massaggi Firenze', 'massaggi-firenze', 'Massaggi Firenze'),
(8, '-Massaggi Foggia', 'massaggi-foggia', 'Massaggi Foggia'),
(8, '-Massaggi Forlì Cesena', 'massaggi-forli-cesena', 'Massaggi Forlì Cesena'),
(8, '-Massaggi Frosinone', 'massaggi-frosinone', 'Massaggi Frosinone'),
(8, '-Massaggi Genova', 'massaggi-genova', 'Massaggi Genova'),
(8, '-Massaggi Gorizia', 'massaggi-gorizia', 'Massaggi Gorizia'),
(8, '-Massaggi Grosseto', 'massaggi-grosseto', 'Massaggi Grosseto'),
(8, '-Massaggi Imperia', 'massaggi-imperia', 'Massaggi Imperia'),
(8, '-Massaggi Isernia', 'massaggi-isernia', 'Massaggi Isernia'),
(8, '-Massaggi L\'Aquila', 'massaggi-l\'aquila', 'Massaggi L\'Aquila'),
(8, '-Massaggi La Spezia', 'massaggi-la-spezia', 'Massaggi La Spezia'),
(8, '-Massaggi Latina', 'massaggi-latina', 'Massaggi Latina'),
(8, '-Massaggi Lecce', 'massaggi-lecce', 'Massaggi Lecce'),
(8, '-Massaggi Lecco', 'massaggi-lecco', 'Massaggi Lecco'),
(8, '-Massaggi Livorno', 'massaggi-livorno', 'Massaggi Livorno'),
(8, '-Massaggi Lodi', 'massaggi-lodi', 'Massaggi Lodi'),
(8, '-Massaggi Lucca', 'massaggi-lucca', 'Massaggi Lucca'),
(8, '-Massaggi Macerata', 'massaggi-macerata', 'Massaggi Macerata'),
(8, '-Massaggi Mantova', 'massaggi-mantova', 'Massaggi Mantova'),
(8, '-Massaggi Massa Carrara', 'massaggi-massa-carrara', 'Massaggi Massa Carrara'),
(8, '-Massaggi Matera', 'massaggi-matera', 'Massaggi Matera'),
(8, '-Massaggi Medio Campidano', 'massaggi-medio-campidano', 'Massaggi Medio Campidano'),
(8, '-Massaggi Messina', 'massaggi-messina', 'Massaggi Messina'),
(8, '-Massaggi Milano', 'massaggi-milano', 'Massaggi Milano'),
(8, '-Massaggi Modena', 'massaggi-modena', 'Massaggi Modena'),
(8, '-Massaggi Monza Brianza', 'massaggi-monza-e-della-brianza', 'Massaggi Monza Brianza'),
(8, '-Massaggi Napoli', 'massaggi-napoli', 'Massaggi Napoli'),
(8, '-Massaggi Novara', 'massaggi-novara', 'Massaggi Novara'),
(8, '-Massaggi Nuoro', 'massaggi-nuoro', 'Massaggi Nuoro'),
(8, '-Massaggi Ogliastra', 'massaggi-ogliastra', 'Massaggi Ogliastra'),
(8, '-Massaggi Olbia Tempio', 'massaggi-olbia-tempio', 'Massaggi Olbia Tempio'),
(8, '-Massaggi Oristano', 'massaggi-oristano', 'Massaggi Oristano'),
(8, '-Massaggi Padova', 'massaggi-padova', 'Massaggi Padova'),
(8, '-Massaggi Palermo', 'massaggi-palermo', 'Massaggi Palermo'),
(8, '-Massaggi Parma', 'massaggi-parma', 'Massaggi Parma'),
(8, '-Massaggi Pavia', 'massaggi-pavia', 'Massaggi Pavia'),
(8, '-Massaggi Perugia', 'massaggi-perugia', 'Massaggi Perugia'),
(8, '-Massaggi Pesaro Urbino', 'massaggi-pesaro-e-urbino', 'Massaggi Pesaro Urbino'),
(8, '-Massaggi Pescara', 'massaggi-pescara', 'Massaggi Pescara'),
(8, '-Massaggi Piacenza', 'massaggi-piacenza', 'Massaggi Piacenza'),
(8, '-Massaggi Pisa', 'massaggi-pisa', 'Massaggi Pisa'),
(8, '-Massaggi Pistoia', 'massaggi-pistoia', 'Massaggi Pistoia'),
(8, '-Massaggi Pordenone', 'massaggi-pordenone', 'Massaggi Pordenone'),
(8, '-Massaggi Potenza', 'massaggi-potenza', 'Massaggi Potenza'),
(8, '-Massaggi Prato', 'massaggi-prato', 'Massaggi Prato'),
(8, '-Massaggi Ragusa', 'massaggi-ragusa', 'Massaggi Ragusa'),
(8, '-Massaggi Ravenna', 'massaggi-ravenna', 'Massaggi Ravenna'),
(8, '-Massaggi Reggio Calabria', 'massaggi-reggio-calabria', 'Massaggi Reggio Calabria'),
(8, '-Massaggi Reggio Emilia', 'massaggi-reggio-emilia', 'Massaggi Reggio Emilia'),
(8, '-Massaggi Rieti', 'massaggi-rieti', 'Massaggi Rieti'),
(8, '-Massaggi Rimini', 'massaggi-rimini', 'Massaggi Rimini'),
(8, '-Massaggi Roma', 'massaggi-roma', 'Massaggi Roma'),
(8, '-Massaggi Rovigo', 'massaggi-rovigo', 'Massaggi Rovigo'),
(8, '-Massaggi Salerno', 'massaggi-salerno', 'Massaggi Salerno'),
(8, '-Massaggi Sassari', 'massaggi-sassari', 'Massaggi Sassari'),
(8, '-Massaggi Savona', 'massaggi-savona', 'Massaggi Savona'),
(8, '-Massaggi Siena', 'massaggi-siena', 'Massaggi Siena'),
(8, '-Massaggi Siracusa', 'massaggi-siracusa', 'Massaggi Siracusa'),
(8, '-Massaggi Sondrio', 'massaggi-sondrio', 'Massaggi Sondrio'),
(8, '-Massaggi Taranto', 'massaggi-taranto', 'Massaggi Taranto'),
(8, '-Massaggi Teramo', 'massaggi-teramo', 'Massaggi Teramo'),
(8, '-Massaggi Terni', 'massaggi-terni', 'Massaggi Terni'),
(8, '-Massaggi Torino', 'massaggi-torino', 'Massaggi Torino'),
(8, '-Massaggi Trapani', 'massaggi-trapani', 'Massaggi Trapani'),
(8, '-Massaggi Trento', 'massaggi-trento', 'Massaggi Trento'),
(8, '-Massaggi Treviso', 'massaggi-treviso', 'Massaggi Treviso'),
(8, '-Massaggi Trieste', 'massaggi-trieste', 'Massaggi Trieste'),
(8, '-Massaggi Udine', 'massaggi-udine', 'Massaggi Udine'),
(8, 'Massaggi Varese', 'massaggi-varese', 'Massaggi Varese'),
(8, '-Massaggi Venezia', 'massaggi-venezia', 'Massaggi Venezia'),
(8, '-Massaggi Verbano Cusio Ossola', 'massaggi-verbano-cusio-ossola', 'Massaggi Verbano Cusio Ossola'),
(8, '-Massaggi Vercelli', 'massaggi-vercelli', 'Massaggi Vercelli'),
(8, '-Massaggi Verona', 'massaggi-verona', 'Massaggi verona'),
(8, '-Massaggi Vibo Valentia', 'massaggi-vibo-valentia', 'Massaggi Vibo Valentia'),
(8, '-Massaggi Vicenza', 'massaggi-vicenza', 'Massaggi Vicenza'),
(8, '-Massaggi Viterbo', 'massaggi-viterbo', 'Massaggi Viterbo');